---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: clickhouse-pv
  namespace: datazip
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath: 
    path: /etc/clickhouse/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - minikube
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clickhouse-pvc
  namespace: datazip
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse
  namespace: datazip
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      nodeSelector:
        kubernetes.io/hostname: minikube
      containers:
      - name: clickhouse
        image: docker.io/clickhouse/clickhouse-server@sha256:740ac03ad65eb6f6690f78a8a224b1c94f0a57a2567e66fbb7ff7327e8fe1e90
        ports:
        - containerPort: 8123 # HTTP Interface
        - containerPort: 9000 # Native Interface
        - containerPort: 9009 # Internal replication
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:
        - name: clickhouse-data
          mountPath: /var/lib/clickhouse
        readinessProbe:
          httpGet:
            path: /
            port: 8123
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /
            port: 8123
          initialDelaySeconds: 10
          periodSeconds: 15
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
      volumes:
      - name: clickhouse-data
        persistentVolumeClaim:
          claimName: clickhouse-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  namespace: datazip
spec:
  selector:
    app: clickhouse
  ports:
  - name: http
    port: 8123
    targetPort: 8123
  - name: native
    port: 9000
    targetPort: 9000
  - name: replication
    port: 9009
    targetPort: 9009
  type: NodePort
