bootstrapScript: |
  #!/bin/bash
  pip install psycopg2-binary==2.9.6 \
    sqlalchemy-bigquery==1.6.1 \
    clickhouse-connect \
    elasticsearch-dbapi==0.2.5 &&\
  if [ ! -f ~/bootstrap ]; then echo "Running Superset with uid {{ .Values.runAsUser }}" > ~/bootstrap; fi

configOverrides: 
    secret: |
      SECRET_KEY = 'IgZ1glA/W8E1hCOe/d5XoE9oBJpgcZnsg1Wj5dlFriBkUnQZmxoM9Gs/'  

resources: 
   limits:
     cpu: 1
     memory: 1Gi
   requests:
     cpu: 500m
     memory: 512Mi

supersetWorker:
  resources: 
     limits:
       cpu: 1
       memory: 2Gi
     requests:
       cpu: 500m
       memory: 1Gi  